### ISSUE TITLE
Implement Stock Management basic logic

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#107]
[Read the swagger description here](https://swagger.altzone.fi/#/Stock)

[See the DB structure for Stock model here](https://github.com/Alt-Org/Altzone-Server?tab=readme-ov-file#db-schema)

[Example endpoint with explanations can be found here](https://github.com/Alt-Org/Altzone-Server/tree/main/src/characterClass)

## Tasks:

- [ ] Get Stock by _id endpoint: Fetches details of a specific Stock by its _id.

    _Description_: Implement the endpoint to fetch details of a specific Stock by its _id field. Everybody can read any Stock data.

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller)

 - [x] Get All Stocks endpoint: Fetches a paginated list of all created Stocks of all Clans.

    _Description_: Implement the endpoint to fetch a paginated list of all created Stocks of all Clans.

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller)

 - [x] Write a public service method for creating a new Stock.

     _Description_: Implement the endpoint for creating a new Stock. I will be used by other modules later.

    _Acceptance Criteria_:
        - Creates new Stock in DB
        - JSDocs
 
 - [x] Write a public service method for updating cells count of the Stock.

     _Description_: Implement the method for updating cells count of the Stock with specified _id. It will be used by other modules later.

    _Acceptance Criteria_:
        - Updates Stock's cells count in DB
        - JSDocs

- [x] Write a public service method for reading a Stock.

     _Description_: Implement the method for reading a Stock by _id in DB

    _Acceptance Criteria_:
        - Reads Stock in DB
        - Returns ServiceError array with error NOT_FOUND if the Stock can not be found
        - JSDocs

- [x] Write a public service method for updating a Stock.

     _Description_: Implement the method for updating a Stock by _id in DB

    _Acceptance Criteria_:
        - Updates Stock in DB
        - Returns ServiceError array with error NOT_FOUND if the Stock can not be found
        - JSDocs

 - [x] Write a public service method for deleting the Stock.

     _Description_: Implement the method for deleting the Stock with specified _id. Notice, that later this method will need to be changed, to remove also all associated rooms and their items. It will be used by other modules later.

    _Acceptance Criteria_:
        - Removes Stock from DB
        - JSDocs

**Comment by MikhailDeriabin** [comment]
@apulkGIT 

In the future, if you have questions for the new task, please left a comment below that new task, not below an old one.

> Hi!
> 
> I was trying to do the next task and found problems:
> 
> - by changing createStock to as in DB structure there is a bug with
> src/clan/service.ts, it tries to create clanStock as type CreateStockDto
> and I do not know how to put there all information, especially item_id[]
>
> - I do not know how to update stock by only in it's cellCount, I don't
> know should I fetch old stock object by it's id and put the new
> cellCount to it and save to database (however I could not do not know
> logic of this.basicService.readOneById<StockDto>(_id) (it's a promise))
>
> - last, when deleting stock do I have to delete also all rooms and items
> that are connected to stock meaning the id's only or the whole Dto's
> that are in database?


- For now, you can comment out the part, which creates the Stock, as well as adding new Items to the Stock in the clan.service.ts. 
```ts
79     const clanStock: CreateStockDto = {
            type: 1,
            rowCount: 5,
            columnCount: 5,
            clan_id: clanResp.data.Clan._id
        }
        const stockResp = await this.stockService.createOne(clanStock);
        if (!stockResp || stockResp instanceof MongooseError)
            return clanResp;

        clanResp.data.Clan.Stock = stockResp.data.Stock;
```
```ts
117  //Add default items to clan's stock
        const items: CreateItemDto[] = getDefaultItems(stockResp.data.Stock._id,roomResp.data.Room._id);
        await this.itemService.createMany(items);
```
- Yes, you should get the data of the Stock, then add the specified amount of cells and update the Stock data in DB with the new value. About the JS Promises you can [read here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) and about Promise awaiting [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await)
- No, you do not have to delete anything else but the Stock itself.

**Comment by apulkGIT** [comment]
> @apulkGIT [1]
> 
> In the future, if you have questions for the new task, please left a
> comment below that new task, not below an old one.
> 
>> Hi!
>> 
>> I was trying to do the next task and found problems:
>> 
>> *
>> 
>> by changing createStock to as in DB structure there is a bug with
>> src/clan/service.ts, it tries to create clanStock as type
>> CreateStockDto
>> and I do not know how to put there all information, especially
>> item_id[]
>> *
>> 
>> I do not know how to update stock by only in it's cellCount, I don't
>> know should I fetch old stock object by it's id and put the new
>> cellCount to it and save to database (however I could not do not
>> know
>> logic of this.basicService.readOneById(_id) (it's a promise))
>> *
>> 
>> last, when deleting stock do I have to delete also all rooms and
>> items
>> that are connected to stock meaning the id's only or the whole Dto's
>> that are in database?
> 
>  	* For now, you can comment out the part, which creates the Stock, as
> well as adding new Items to the Stock in the clan.service.ts.
> 
> 79     const clanStock: CreateStockDto = {
>             type: 1,
>             rowCount: 5,
>             columnCount: 5,
>             clan_id: clanResp.data.Clan._id
>         }

I have put array to CreateStockDto (item_id: string[]). Do I take it off 
since I can't do it without stockResp.data.Stock_id?

>         const stockResp = await
> this.stockService.createOne(clanStock);
>         if (!stockResp || stockResp instanceof MongooseError)
>             return clanResp;
> 
>         clanResp.data.Clan.Stock = stockResp.data.Stock;
> 
> 117  //Add default items to clan's stock
>         const items: CreateItemDto[] =
> getDefaultItems(stockResp.data.Stock._id,roomResp.data.Room._id);
>         await this.itemService.createMany(items);
> 
>  	* Yes, you should get the data of the Stock, then add the specified
> amount of cells and update the Stock data in DB with the new value.
> About the JS Promises you can read here [2] and about Promise awaiting
> here [3]

I tried putting Promise.then (x => { stock = x; }); or something 
similar, but I do not know x and not know how to get Stock.

>  	* No, you do not have to delete anything else but the Stock itself.

-Antti

**Comment by MikhailDeriabin** [comment]
@apulkGIT 

- There is no need for the item_ids array. The Stock does not have to know about the items inside it.
- Please read the article about awaiting Promises I provided earlier

**Comment by apulkGIT** [comment]
> @apulkGIT [1]
> 
>  	* There is no need for the item_ids array. The Stock does not have
> to know about the items inside it.
>  	* Please read the article about awaiting Promises I provided earlier

I get following error:

src/clan/clan.service.ts:86:46 - error TS2339: Property 'data' does not 
exist on type 'StockDto | ServiceError[]'.
   Property 'data' does not exist on type 'StockDto'.

            const stockResp = await 
this.stockService.createOne(clanStock);
            if (!stockResp || stockResp instanceof MongooseError)
               return clanResp;
86         clanResp.data.Clan.Stock = stockResp.data.Stock;

Where can I find structure of stockResp?

**Comment by MikhailDeriabin** [comment]
@apulkGIT 
As I have written previously you can comment out this part of code, you do not have to handle Stock creation in clan.service.ts

**Comment by apulkGIT** [comment]
> @apulkGIT [1]
> As I have written previously you can comment out this part of code,
> you do not have to handle Stock creation in clan.service.ts

OK. I still have one problem, it is the cellCount update.

async updateOneBycellcount(Stock: UpdateStockDto) {
        const {_id, cellCount, ...fieldsToUpdate} = Stock;
        this.basicService.readOneById<StockDto>(_id).then ( x => {
          console.log(x);
          x.cellCount = cellCount;
          return this.basicService.updateOneById(_id, x);
        });
     }

I don't know why do it give following error:

Property 'cellCount' does not exist on type 'ServiceError[]'.

while console.log(x) gives the StockDto struct:

{
   _id: new ObjectId("66c20e694b97244ecf30a07d"),
   cellCount: 1,
   clan_id: new ObjectId("66c2028df0f4bbc6be07a240"),
   __v: 0,
   id: '66c20e694b97244ecf30a07d'
}

-Antti

**Comment by MikhailDeriabin** [comment]
@apulkGIT 
1. You should use the _await_ for Promises awaiting, not _then()_. It is easier to write and read:

```ts
const myResp = await myAsyncFunc();
// Easier to read than it:
myAsyncFunc.then((data) => {
  const myResp = data;
});
```

2. The updateOneByCellcount() should accept the _id field of the Stock to update and the cell amount, not the whole UpdateStockDto object. 
3. You are getting some ServiceError instead of the Stock, there can be different reasons why. You can print the returned value to the terminal and see the reason of the error.

**Comment by apulkGIT** [comment]
> @apulkGIT [1]
> 
>  	* You should use the _await_ for Promises awaiting, not _then()_. It
> is easier to write and read:
> 
> const myResp = await myAsyncFunc();
> // Easier to read than it:
> myAsyncFunc.then((data) => {
>   const myResp = data;
> });

I changed to this:

async updateOneBycellcount(Stock: UpdateStockDto) {
        const {_id, cellCount, ...fieldsToUpdate} = Stock;
        const x = await this.basicService.readOneById<StockDto>(_id);
        fieldsToUpdate.clan_id = x.clan_id;
        console.log("x"+x);
        console.log("fTU"+fieldsToUpdate);
        return this.basicService.updateOneById(_id, fieldsToUpdate);
}

i still get error:

Property 'clan_id' does not exist on type 'StockDto | ServiceError[]'.
   Property 'clan_id' does not exist on type 'ServiceError[]'.

111        fieldsToUpdate.clan_id = x.clan_id;

>  	* The updateOneByCellcount() should accept the _id field of the
> Stock to update and the cell amount, not the whole UpdateStockDto
> object.

Do I have to put to basicService new function that updates only 
cellCount? If how to do it?

>  	* You are getting some ServiceError instead of the Stock, there can
> be different reasons why. You can print the returned value to the
> terminal and see the reason of the error.

-Antti

**Comment by MikhailDeriabin** [comment]
@apulkGIT 
> i still get error:

You should first print the value of the x, and then try to access the _clan_id_ field. You can get two types of responses from the _BasicService_ read methods: found objects or array of errors. Before accessing any field from the response, you should first check the type of it, for example with _isServiceError()_ function from the ServiceError.ts or with [_instanceof_ operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof). Please also read the JSDocs for these methods in your IDE.

> Do I have to put to basicService new function that updates only cellCount? If how to do it?

2. No, you should not change the code of the _BasicService_ class. You need to update the _cellCount_ field only while calling the _updateOneById()_ method.

**Comment by apulkGIT** [comment]
> @apulkGIT [1]
> 
>> i still get error:
> 
> You should first print the value of the x, and then try to access the
> _clan_id_ field. You can get two types of responses from the
> _BasicService_ read methods: found objects or array of errors. Before
> accessing any field from the response, you should first check the type
> of it, for example with _isServiceError()_ function from the
> ServiceError.ts or with _instanceof_ operator [2]. Please also read
> the JSDocs for these methods in your IDE.

print?

Now it's this way

async updateOneBycellcount(Stock: UpdateStockDto) {
        const {_id, ...fieldsToUpdate} = Stock;
        const x = await this.basicService.readOneById<StockDto>(_id);
        if (!x || x instanceof MongooseError)
          throw new NotFoundException('Stock with that id do not exist');
        fieldsToUpdate.clan_id = x.clan_id;
        //fieldsToUpdate.clan_id = x.data[x.metaData.dataKey].clan_id;
        //console.log("x"+x);
        //console.log("fTU"+fieldsToUpdate);
        return this.basicService.updateOneById(_id, fieldsToUpdate);
     }

I do not still get how to get clan_id from x, it would be easier if you 
just tell the answer.

**Comment by MikhailDeriabin** [comment]
@apulkGIT 

Here is the method implementation, but in future it would be nice if you could do it by yourself.

```ts
public updateStockCellCount = async (_id: string, cellCountChange: number) => {
    const dbResp = await this.basicService.readOneById<StockDto>(_id);
    if(isServiceError(dbResp))
        return dbResp as ServiceError[];

    const stock = dbResp as unknown as Stock;

    const { cellCount } = stock;

    const requestedCellCount = cellCount + cellCountChange;
    const newCellCount = requestedCellCount < 0 ? 0 : requestedCellCount;

    return this.basicService.updateOneById(_id, { cellCount: newCellCount });
}
```

**Comment by apulkGIT** [comment]
Hi!

I am leaving the Psyche. So what am I going to do with ALT-server? Do I 
delete the files from my system or save it couple of weeks?

-Antti

**Comment by MikhailDeriabin** [comment]
@apulkGIT 
Ok, you can delete the project from your PC
