### ISSUE TITLE
Implement Item basic logic

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#108]
[Read the swagger description here](https://swagger.altzone.fi/#/Item)

[See the DB structure here](https://github.com/Alt-Org/Altzone-Server?tab=readme-ov-file#db-schema)

[Example endpoint with explanations can be found here](https://github.com/Alt-Org/Altzone-Server/tree/main/src/characterClass)

## Tasks:

- [ ] Get Item by _id endpoint: Fetches details of a specific Item by its _id.

    _Description_: Implement the endpoint to fetch details of a specific Item by its _id field.

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller)

- [ ] Write public service method for creating a new Item.

    _Description_: Write public service method for creating a new Item in DB. It will be used in another module later.

    _Acceptance Criteria_:
        - Creates a new Item in DB
        - JSDocs

- [ ] Write public service method for updating Item by specified _id

    _Description_: Write public service method for creating a new Item in DB.

    _Acceptance Criteria_:
        - Updates Item in DB if it is found in DB
        - Returns ServiceError array with error NOT_FOUND if the Item can not be found
        - JSDocs

- [ ] Write public service method for deleting Item by specified _id

    _Description_: Write public service method for deleting an Item from DB.

    _Acceptance Criteria_:
        - deletes Item from DB if it is found in DB
        - Returns ServiceError array with error NOT_FOUND if the Item can not be found
        - JSDocs

**Comment by apulkGIT** [comment]
Hi!

I was trying to do the next task and found problems:

- by changing createStock to as in DB structure there is a bug with 
src/clan/service.ts, it tries to create clanStock as type CreateStockDto 
and I do not know how to put there all information, especially item_id[]
- I do not know how to update stock by only in it's cellCount, I don't 
know should I fetch old stock object by it's id and put the new 
cellCount to it and save to database (however I could not do not know 
logic of this.basicService.readOneById<StockDto>(_id) (it's a promise))
- last, when deleting stock do I have to delete also all rooms and items 
that are connected to stock meaning the id's only or the whole Dto's 
that are in database?

-Antti
