### ISSUE TITLE
Implement SoulHome Management basic logic

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#109]
[Read the swagger description here](https://swagger.altzone.fi/#/SoulHome)

[See the DB structure here](https://github.com/Alt-Org/Altzone-Server?tab=readme-ov-file#db-schema)

[Example endpoint with explanations can be found here](https://github.com/Alt-Org/Altzone-Server/tree/main/src/characterClass)

## Tasks:

- [x] Get SoulHome data endpoint

    _Description_: Implement the endpoint to fetch details of a SoulHome for logged-in user. The logged-in user should be accessible via request['user'] and based on this user info appropriate SoulHome should be found. If user is not in any clan 404 should be returned

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller)

- [x] Write a public service method for creating a new SoulHome.

     _Description_: Implement the method for creating a new SoulHome in DB

    _Acceptance Criteria_:
        - Creates new Stock in DB
        - JSDocs

- [x] Write a public service method for reading a Soulhome.

     _Description_: Implement the method for reading a SoulHome by _id in DB

    _Acceptance Criteria_:
        - Reads SoulHome in DB
        - Returns ServiceError array with error NOT_FOUND if the SoulHome can not be found
        - JSDocs

- [x] Write a public service method for updating a Soulhome.

     _Description_: Implement the method for updating a SoulHome by _id in DB

    _Acceptance Criteria_:
        - Updates SoulHome in DB
        - Returns ServiceError array with error NOT_FOUND if the SoulHome can not be found
        - JSDocs

- [x] Write a public service method for deleting a Soulhome.

     _Description_: Implement the method for deleting a SoulHome by _id in DB

    _Acceptance Criteria_:
        - Deletes SoulHome in DB
        - Returns ServiceError array with error NOT_FOUND if the SoulHome can not be found
        - JSDocs
