### ISSUE TITLE
Implement Room Management basic Logic

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#110]
[Read the swagger description here](https://swagger.altzone.fi/#/Room)

[See the DB structure here](https://github.com/Alt-Org/Altzone-Server?tab=readme-ov-file#db-schema)

[Example endpoint with explanations can be found here](https://github.com/Alt-Org/Altzone-Server/tree/main/src/characterClass)

## Tasks:

- [x] Get Room by _id endpoint: Fetches details of a specific Room by its _id.

    _Description_: Implement the endpoint to fetch details of a specific Room by its _id field. Only Clan members can read Room data.

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller) 

- [x] Get all Rooms endpoint

    _Description_: Implement the endpoint to fetch all Rooms for the logged-in user. The logged-in user data can be retrieved from request['user']. If user is not in that Clan the 404 should be returned.

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller) 

- [x] Update Room endpoint

    _Description_: Implement the endpoint to update Room's data for the logged-in user. The logged-in user data can be retrieved from request['user']. If user is not in that Clan the 404 should be returned.

    _Acceptance Criteria_:
        - Works as written in swagger
        - JSDocs for all classes and methods (except for controller) 

- [x] Write a public service method for creating a new Room.

     _Description_: Implement the method for creating a new Room in DB

    _Acceptance Criteria_:
        - Creates new Room in DB
        - JSDocs

- [x] Write a public service method for reading a Room.

     _Description_: Implement the method for reading a Room by _id in DB

    _Acceptance Criteria_:
        - Reads Room in DB
        - Returns ServiceError array with error NOT_FOUND if the Room can not be found
        - JSDocs

- [x] Write a public service method for updating a Room.

     _Description_: Implement the method for updating a Room by _id in DB

    _Acceptance Criteria_:
        - Updates Room in DB
        - Returns ServiceError array with error NOT_FOUND if the Room can not be found
        - JSDocs

- [x] Write a public service method for deleting a Room.

     _Description_: Implement the method for deleting a Room by _id in DB

    _Acceptance Criteria_:
        - Deletes Room in DB
        - Returns ServiceError array with error NOT_FOUND if the Room can not be found
        - JSDocs
