### ISSUE TITLE
Item moving logic

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#112]
[Read the swagger description here](https://swagger.altzone.fi/#/Item/post_item_move)

Items service moving logic

## Tasks:

- [x] Write public service method for moving Items from Room to Stock.

    _Description_: Write public service method for moving Items to Stock by specified _ids. It should accept array of item _ids and the stock _id as arguments, update the stock_id field for the Items, as well as make room_id field null

    _Acceptance Criteria_:
        - Updates Item in DB if it is found in DB
        - Returns ServiceError array with error NOT_FOUND if no Items (at all) can not be found
        - Returns ServiceError array with error NOT_FOUND if the Stock can not be found
        - JSDocs

- [x] Write public service method for moving Items from Stock to Room.

    _Description_: Write public service method for moving Items to Room by specified _ids. It should accept array of item _ids and the room _id as parameters, update the room_id field for the Items, as well as make stock_id field null

    _Acceptance Criteria_:
        - Updates Item in DB if it is found in DB
        - Returns ServiceError array with error NOT_FOUND if any Items (at all) can not be found
        - Returns ServiceError array with error NOT_FOUND if the Room can not be found
        - JSDocs

- [x] Write Item moving endpoint (/item/move POST)

   Write Item moving endpoint as described in swagger

**Comment by PlayJeri** [comment]
Oliko tarkoitus pystyä liikuttamaan yhtä vai useampaa itemiä kerrallaan, kun näissä service method vaatimuksissa on, että argumenttina pitää ottaa vastaan item_ids array ja swaggering mukaan tuo item/move endpoint ottaa vastaan vaan yhden item_id:n. Eli teenkö niin kuin swaggerissa on kuvailtu, jos nämä service methodit ovat ensisijaisesti tätä endpointtia varten? @MikhailDeriabin

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

Tarvitaan siis siirtää muutama tavaraa paikasta toiseen, silloin kun ryöstetään niitä, eli ne metoodit ovat tulevaisuutta varten. 

Jos haluat voit tehdä molemmat metoodit, yksi joka siirtää yksi tavara ja toinen, joka siirtää heti muutamaa, sinä päätät
