### ISSUE TITLE
Add statistics data to Player model

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#231]
### General description

There should be data available about the Player stats, such as played games count, won games count, sent messages. All the data used to determine player place in a leaderboard.

### Things to notice

This data should also be available on /leaderboard response.

Player should not be able to set or update these values, they are read only for client side.

### Tasks

- [x] Add fields to Player schema `gameStatistics` object: playedBattles, wonBattles, diamondsAmount, startedVotings, participatedVotings. Default is 0.
- [x] Add counting for playedGames field, when game is played.
- [x] Add counting for wonGamesfield, when game is won.
