### ISSUE TITLE
BasicService class tests

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#263]
### General description

Add tests for all BasicService class methods.

### Things to notice

Use the in-memory DB in all tests, do not write any mocks

### Tasks

- [ ] write test for `createOne()`
- [ ] write test for `createMany()`
- [ ] write test for `readOneById()`
- [ ] write test for `readOne()`
- [ ] write test for `readMany()`
- [ ] write test for `updateOneById()`
- [ ] write test for `updateOne()`
- [ ] write test for `updateMany()`
- [ ] write test for `deleteOneById()`
- [ ] write test for `deleteOne()`
- [ ] write test for `deleteMany()`
- [ ] write test for `convertMongooseToServiceErrors()`

**Comment by MikhailDeriabin** [comment]
Expected task time: 1h, actual: 6h
