### ISSUE TITLE
write tests for Counter class

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#264]
### General description

Add tests for all Counter class methods.

### Things to notice

Use the in-memory DB in all tests, do not write any mocks

### Tasks

- [x] write test for `decrease()`
- [x] write test for `decreaseById()`
- [x] write test for `decreaseOnOne()`
- [x] write test for `decreaseByIdOnOne()`
- [x] write test for `increase()`
- [x] write test for `increaseById()`
- [x] write test for `increaseOnOne()`
- [x] write test for `increaseByIdOnOne()`
