### ISSUE TITLE
add tests for MQTTConnector

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#266]
### General description

Add tests for all MQTTConnector methods.

### Things to notice

Use mock of the mqtt library instead of actual one

### Tasks

- [x] write test for `getInstance()`
- [x] write test for `connect()`
- [x] write test for `disconnect()`
- [x] write test for `publish()`

**Comment by MikhailDeriabin** [comment]
Estimated 0.5h, actual 0.75h
