### ISSUE TITLE
Add tests for common/function module

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#273]
### General description

Add tests for all exported functions from the common/function folder.

### Tasks

- [x] write test for `addUniqueArrayElements()`
- [x] write test for `deleteArrayElements()`
- [x] write test for `deleteNotUniqueArrayElements()`
- [x] write test for `getTimeSince()`
- [x] write test for `passed()`

**Comment by MikhailDeriabin** [comment]
Estimated 0.5h, actual 0.25h
