### ISSUE TITLE
Add tests for isEntityExists class

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#276]
### General description

Add tests for all isEntityExists class methods.

### Things to notice

Write JSDocs as well

### Tasks

- [x] write test for `validate()`
- [x] write test for `defaultMessage()`
- [x] write JSDocs for isEntityExists class, but not methods

**Comment by MikhailDeriabin** [comment]
Estimated 0.25h, actual 0.75h
