### ISSUE TITLE
Add tests for common/controller folder

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#284]
### General description

Add tests for all functions in common/controller folder.

### Tasks

- [ ] write test for `APIError` constructor
- [ ] write test for `isAPIError()`
- [ ] write test for `convertToAPIError()`
- [ ] write tests for `formatResponse()`

**Comment by MikhailDeriabin** [comment]
Estimated 0.5h, actual 0.5h
