### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#314]
### General description

Make a new release

### Tasks

- [x] check documentation is up-to-date
- [x] change swagger to have endpoints changed in release
- [x] write release notes
- [x] make docker image for release
- [x] put release image to dev server
- [x] save release snap shot
- [x] publish release on server
- [x] publish release on GitHub
