### ISSUE TITLE
write tests for clan module

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#322]
### Tasks

- [x] write tests for ClanService class
- [x] write tests for PlayerCounterFactory class
- [x] write tests for ClanHelperService
- [x] write tests for utils/defaultValues/items.ts
- [x] write tests for JoinService
- [x] write tests for isClanExists()
