### ISSUE TITLE
write tests for clanInventory module

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#323]
### Tasks

- [x] write tests for SoulHomeService class
- [x] write tests for SoulHomeHelperService class
- [x] write tests for RoomService class
- [x] write tests for RoomHelperService class
- [x] write tests for StockService class
- [x] write tests for IsStockExists class
- [x] write tests for ItemService class
- [x] write tests for ItemHelperService class
- [x] write tests for StealTokenGuard class
- [x] write tests for IsItemExists()

**Comment by MikhailDeriabin** [comment]
Actual time 30h = 4d
