### ISSUE TITLE
Feature request: Heartbeat call to keep server (and client) informed of one another.

### ISSUE THREAD

**Issue by BillTheBeast** [Alt-Org/Altzone-Server#342]
## What do you want to see in the API?

Simple endpoint that should receive a call (GET or POST? Not fully sure which one is better) from the client constantly. This interval can be determined later, but it could be anywhere from 0.1s to few seconds. We can initially assume a interval of 1 second.

## How do you think this should work?

This endpoint will receive the call from the client and then acknowledge that it received the message back to the client.
This helps the server to keep track of players that are connected to it and also inform the client that there are changes (chat, voting system, furnitures, clan member, etc.) that the client needs to GET from the server. (Chat messages and votes probably the most important things as the others can just be updated when the client actually needs them but chat messages and the state of each "poll" is reflected in the UI)

These changes could be either stored inside a string/Enum array or probably more sensibly, a byte enum where each byte represent a point of data that should be fetched.

Also if the client doesn't receive the acknowlegde message from the server after certain time it can be assumed that the connection has been lost.

**Comment by MikhailDeriabin** [comment]
@BillTheBeast 

Not sure about that. The client will get updates of the system (votes, tasks etc.) via MQTT, which is more efficient way of handling events notifications. The notifications about messages can come also via MQTT as well, but I did not check the chat system yet.

The data about player being online can be updated once a minute or half a minute, since it is not that critical.

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

## General description

There should be created a mechanism, where the API and the game know of how much players are online and who they are.

## Things to notice

It is also nice to add caching for this data to spare some server resources, if it is not too complicated of course and mb invalidate it every 5 mins or so.

## Tasks

- [ ] Add an endpoint, where client can send a request and notify that it is still online. You probably want to create a separate module that handles that.
- [ ] Add a way to get a list of all of the players being online ATM, both for client and server. For this moment set that if the player hasn't send the request for a 5 min, it will be considered offline, but this time period should be configurable.
- [ ] Add an endpoint for checking how much players are currently online and possibly cache this number. It is required for us to identify whether we can allow new players to play the battle, due to the Photon restriction, which we were discussed in the meeting.
