### ISSUE TITLE
Make release-23-12-2024

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#356]
### General description

Make a new release

### Tasks

- [x] check that documentation is up-to-date:
  1. swagger
  2. ERD
  3. Code architecture
- [x] make merges:
  1. _main_ -> _prod_
  2. _dev_ -> _main_
- [x] make swagger for the release with tag grouping all changed endpoints
- [x] make docker image for release from _main_
- [x] put release image to dev server
- [x] save release snapshot
- [x] write release notes
- [x] publish release and updated swagger on server
- [x] publish release on GitHub
